# EDA jugadores de Fifa
En este informe se busca analizar... 
### (Escribir proposito del informe)
puede ser algo tipo identificar las variables clave para predecir el precio de un jugador y observar el efecto de estas variables sobre el precio.


## Analisis preliminar de base de datos
Primero, descargo la base de datos y obtengo una primera imagen sobre que contiene

In [7]:
import pandas as pd


df = pd.read_csv("./footballData.csv")

print(df.shape)
df.head(4).transpose()

(18944, 106)


0  \
sofifa_id                                              158023   
player_url  https://sofifa.com/player/158023/lionel-messi/...   
short_name                                           L. Messi   
long_name                      Lionel Andrés Messi Cuccittini   
age                                                        33   
...                                                       ...   
lb                                                       62+3   
lcb                                                      52+3   
cb                                                       52+3   
rcb                                                      52+3   
rb                                                       62+3   

                                                            1  \
sofifa_id                                               20801   
player_url  https://sofifa.com/player/20801/c-ronaldo-dos-...   
short_name                                  Cristiano Ronaldo   
long_name                 Cristiano Ronaldo dos Santos Aveiro   
age                                                        35   
...                                                       ...   
lb                                                       61+3   
lcb                                                      54+3   
cb                                                       54+3   
rcb                                                      54+3   
rb                                                       61+3   

                                                            2  \
sofifa_id                                              200389   
player_url  https://sofifa.com/player/200389/jan-oblak/210002   
short_name                                           J. Oblak   
long_name                                           Jan Oblak   
age                                                        27   
...                                                       ...   
lb                                                       32+3   
lcb                                                      33+3   
cb                                                       33+3   
rcb                                                      33+3   
rb                                                       32+3   

                                                            3  
sofifa_id                                              188545  
player_url  https://sofifa.com/player/188545/robert-lewand...  
short_name                                     R. Lewandowski  
long_name                                  Robert Lewandowski  
age                                                        31  
...                                                       ...  
lb                                                       61+3  
lcb                                                      60+3  
cb                                                       60+3  
rcb                                                      60+3  
rb                                                       61+3  

[106 rows x 4 columns]

En el análisis preliminar se observa que la data contiene 106 columnas y 18944 filas.
Por ende, primero se debe identificar que columnas son claves para el análisis y descartar las demás.

In [9]:
df.dtypes

sofifa_id      int64
player_url    object
short_name    object
long_name     object
age            int64
               ...  
lb            object
lcb           object
cb            object
rcb           object
rb            object
Length: 106, dtype: object

In [10]:
df.loc[:,df.isnull().any()].isnull().sum()

club_name                 225
league_name               225
league_rank               225
release_clause_eur        995
player_tags             17536
team_position             225
team_jersey_number        225
loaned_from             18186
joined                    983
contract_valid_until      225
nation_position         17817
nation_jersey_number    17817
pace                     2083
shooting                 2083
passing                  2083
dribbling                2083
defending                2083
physic                   2083
gk_diving               16861
gk_handling             16861
gk_kicking              16861
gk_reflexes             16861
gk_speed                16861
gk_positioning          16861
player_traits           10629
defending_marking       18944
dtype: int64

Al observar las columnas con valores faltantes, y cuantos les faltan, se observa cierta relación entre estas.
Se observan muchos valores faltantes para los traits de arquero, por ende, se decide descartar los arqueros y las columnas con su respectiva información del modelo. Esto es porque se considera que los arqueros requerirían un análisis por separado.

#### Analizo las columnas short_name, long_name y sofifa_id

In [11]:
df.loc[df['short_name'].duplicated(), 'short_name'].count()

1060

In [12]:
df.loc[df['long_name'].duplicated(), 'long_name'].count()

48

In [13]:
df.loc[df['sofifa_id'].duplicated(), 'sofifa_id'].count()

0

Cómo short_name y long_name contienen valores duplicados y sofifa_id no apora inguna información, se decide eliminar las tres columnas y usar el índice para diferenciar a los jugadores.

#### (Es horrible trabajar sin el nombre de los jugadores, pero no hay  ninguna forma linda de justificar trbaajar con long_name)



#### Analizo columna players_positions

In [15]:
type(df['player_positions'][0])

str

La posicion de los jugadores está en formato String, por lo que es conveniente pasarlo a una lista que contenga las posibles posiciones de cada jugador por separado.

In [16]:
df['player_positions']  = [item.split(', ') for item in df['player_positions']]
df['player_positions'].head()

0    [RW, ST, CF]
1        [ST, LW]
2            [GK]
3            [ST]
4       [LW, CAM]
Name: player_positions, dtype: object

### Selecciono columnas para el análisis
Entonces, procedemos a descartar las columnas que carecen de información importante (como player_url, face_id, etc), las que contienen información similar a la de otra columna y que no aporta al análisis (cómo short_name y sofifa_id cuya información se encuentra en long_name, o dob, que informa la fecha de nacimiento del jugador, y mantenemos la edad en vez), en cuánto a atributos de jugador, mantenemos las columnas principales (por ejemplo descartamos attacking_finishing pero mantenemos shooting) ya que buscamos un análisis genérico de los jugadores y consideramos que esos atributos se requerirían para un análisis más puntual por posición. Finalmente, descartamos las columnas ls, st, etc, ya que poseen información sobre como se adapta el jugador para jugar en otras posiciones, lo cuál consideramos reduntante.

Se seleccionan las columnas a utilizar en el analisis:


*   player_id
*   age
*   height_cm
*   weight_kg
*   nationality
*   club_name
*   league_name
*   league_rank
*   team_jersey_number
*   nation_jersey_number
*   overall
*   value_eur
*   wage_eur
*   player_positions
*   preferred_foot
*   skill_moves
*   team_jersey_number
*   pace
*   shooting
*   passing
*   dribbling
*   defending
*   physic

Por ende, en primera instancia se mantienen 22 columnas de las 106 iniciales y se eliminan los jugadores cuya posición sea GK (arquero)

In [36]:
columnas = ['value_eur', 'wage_eur','age', 'height_cm', 'weight_kg', 
            'nationality', 'club_name', 'league_name', 'league_rank', 
            'team_jersey_number', 'nation_jersey_number', 'overall', 
            'player_positions', 'preferred_foot', 'skill_moves', 
            'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']

df = df.loc[['GK' not in item for item in df['player_positions']], columnas]

print(df.shape)
df.head().transpose()

(16860, 22)


0                1  \
player_id                             158023            20801   
value_eur                           67500000         46000000   
wage_eur                              560000           220000   
age                                       33               35   
height_cm                                170              187   
weight_kg                                 72               83   
nationality                        Argentina         Portugal   
club_name                       FC Barcelona         Juventus   
league_name           Spain Primera Division  Italian Serie A   
league_rank                              1.0              1.0   
team_jersey_number                      10.0              7.0   
nation_jersey_number                    10.0              7.0   
overall                                   93               92   
player_positions                [RW, ST, CF]         [ST, LW]   
preferred_foot                          Left            Right   
skill_moves                                4                5   
pace                                    85.0             89.0   
shooting                                92.0             93.0   
passing                                 91.0             81.0   
dribbling                               95.0             89.0   
defending                               38.0             35.0   
physic                                  65.0             77.0   

                                         3                    4  \
player_id                           188545               190871   
value_eur                         80000000             90000000   
wage_eur                            240000               270000   
age                                     31                   28   
height_cm                              184                  175   
weight_kg                               80                   68   
nationality                         Poland               Brazil   
club_name                FC Bayern München  Paris Saint-Germain   
league_name           German 1. Bundesliga       French Ligue 1   
league_rank                            1.0                  1.0   
team_jersey_number                     9.0                 10.0   
nation_jersey_number                   NaN                  NaN   
overall                                 91                   91   
player_positions                      [ST]            [LW, CAM]   
preferred_foot                       Right                Right   
skill_moves                              4                    5   
pace                                  78.0                 91.0   
shooting                              91.0                 85.0   
passing                               78.0                 86.0   
dribbling                             85.0                 94.0   
defending                             43.0                 36.0   
physic                                82.0                 59.0   

                                           5  
player_id                             192985  
value_eur                           87000000  
wage_eur                              370000  
age                                       29  
height_cm                                181  
weight_kg                                 70  
nationality                          Belgium  
club_name                    Manchester City  
league_name           English Premier League  
league_rank                              1.0  
team_jersey_number                      17.0  
nation_jersey_number                     7.0  
overall                                   91  
player_positions                   [CAM, CM]  
preferred_foot                         Right  
skill_moves                                4  
pace                                    76.0  
shooting                                86.0  
passing                                 93.0  
dribbling                               88.0  
defending         

## Plan de Análisis
Establecidas las columnas a utilizar en el análisis, se procede a establecer un plan de análisis. Primer

In [6]:
import seaborn as sns   
sns.boxplot(x=df['value_eur'])

#Valores anormales

<AxesSubplot: xlabel='value_eur'>